#!/bin/bash

if [ -z "$1" ]; then
    echo "file is missing as first param"
    exit -1
fi

FILE="$1"
DATE1="$(date +'%Y-%m-%d %H')"
DATE2="$(date +'%Y-%m-%d %H' -d '1 hour ago')"

ERRORS=$(egrep "($DATE1|$DATE2)" $FILE | grep -i error | wc -l | tr -d ' ')
if [ "$ERRORS" != "0" ]; then
    echo "$FILE CRITICAL appears $ERRORS lines"
    exit 2
fi

WARNINGS="$(egrep '($DATE1|$DATE2)' $FILE | grep -i warn | wc -l | tr -d ' ')"
if [ "$WARNINGS" != "0" ]; then
    echo "$FILE WARNING appears $WARNINGS lines"
    exit 1
fi

echo "$FILE OK no errors nor warnings in logs"
exit 0

