#!/bin/bash

UNKNOWN_STATE=3
CRITICAL_STATE=2
WARNING_STATE=1
OK_STATE=0

if [ -z "$1" ]; then
    echo "[\"UNKNOWN\", \"you have to specify a binary Erlang script path\"]"
    exit $UNKNOWN_STATE
fi

cd $(dirname $1)/..

DAEMON="$1"
NAME="$(basename $DAEMON)"
PROC="$($DAEMON ping &> /dev/stdout)"

if [ "$PROC" == "pong" ]; then
    echo "[\"OK\", \"$NAME process is up\"]"
    exit $OK_STATE
fi

echo "[\"FAIL\", \"$NAME process is DOWN!\"]"
exit $CRITICAL_STATE
